hoeing:
  enabled: true
  cancel-on-move: true
  time: 5 #in seconds
  messages:
    start:
      enabled: true
      message: "&cHoeing started, do not move!"
    cancelled:
      enabled: true
      message: "&4You moved, hoeing cancelled!"

bone-meal:
  enabled: true #note: this won't affect non-farming blocks (ex. saplings)
  crops-enabled: true #wheat seeds
  pumpkin-stem: true
  melon-stem: true