hoeing:
  enabled: true
  cancel-on-move: true
  time: 3.5 #in seconds
  messages:
    start:
      enabled: true
      message: "&cHoeing started, do not move!"
    cancelled:
      enabled: true
      message: "&4You moved, hoeing cancelled!"
  set-to-dirt-after-seed-break: true

bone-meal:
  enabled: true #note: this won't affect non-farming blocks (ex. saplings)
  crops-enabled: true #wheat seeds
  pumpkin-stem: true
  melon-stem: true
  carrot: true
  potato: true
  beetroot-block: true #only for 1.9+

commands:
  givesprinkler:
    drop-when-inv-full: true #if false it will not give the item at all

sprinkler:
  range: 5