hoeing:
  enabled: true
  cancel-on-move: true
  time: 5 #in seconds
  messages:
    start:
      enabled: true
      message: "&cHoeing started, do not move!"
    cancelled:
      enabled: true
      message: "&4You moved, hoeing cancelled!"

bone-meal:
  enabled: true #note: this won't affect non-farming blocks (ex. saplings)
  crops-enabled: true #wheat seeds
  pumpkin-stem: true
  melon-stem: true

commands:
  giveitem:
    drop-when-inv-full: true #if false it will not give the item at all

set-to-dirt-after-seed-break: true

sprinkler:
  range: 5